blogger/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.get_blog_list, name="index"),
    path('blogger/blogger/<int:blog_id>', views.blog, name="blog_by_id"),
    path('blogger/<int:post_id>', views.like, name="post_by_id"),
    path('login', views.log_in, name="login"),
    path('logout', views.log_out, name="logout"),
    path('signup', views.sign_up, name="signup"),
    path('<int:blog_id>/create_post_', views.create_post_, name="create_post_"),
    path('<int:blog_id>/edit_blog', views.edit_blog, name="edit_blog"),
    path('<int:blog_id>/list', views.list, name="list"),
    path('<int:comment_id>', views.complaint, name="complaint"),
]

siteroot/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogger/', include('blogger.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogger/models.py
from django.db.models import *
from django.contrib.auth.models import User


class Blog(Model):
    title = CharField(max_length=50)
    created_at = DateTimeField('creation timestamp', auto_now_add=True)
    updated_at = DateTimeField('update timestamp', auto_now=True)
    author = ForeignKey(User, on_delete=CASCADE, default=1)
    avatar = ImageField(upload_to='media/user_photo', default='avatar.png')
    views = PositiveIntegerField(default=0)
    bio = TextField(max_length=300, default="I'm Empty")
    permission = BooleanField(default=False)

    def __str__(self):
        return str(self.title)


class Post(Model):
    blog = ForeignKey(Blog, on_delete=CASCADE)
    subject = CharField(max_length=50)
    text = TextField(max_length=1000)
    created_at = DateTimeField('creation timestamp', auto_now_add=True)
    updated_at = DateTimeField('update timestamp', auto_now=True)
    # Information about building
    address = CharField(max_length=80, default='NN')
    photo = ImageField(upload_to='media/user_photo/')
    likes = PositiveIntegerField(default=0)
    # year_of_construction = ????

    def __str__(self):
        return str(self.subject)


class Like(Model):
    user = ForeignKey(User, on_delete=CASCADE)
    post = ForeignKey(Post, on_delete=CASCADE)
    created = DateTimeField(auto_now_add=True)


class Follow(Model):
    following = ForeignKey(User, on_delete=CASCADE, related_name='following')
    follower = ForeignKey(User, on_delete=CASCADE, related_name='follower')
    created = DateTimeField(auto_now_add=True)


class Comment(Model):
    comment_post = CharField(max_length=300)
    author = ForeignKey(User, on_delete=CASCADE)
    commented_image = ForeignKey(Post, on_delete=CASCADE)
    complaints = PositiveIntegerField(default=0)
    created_at = DateTimeField('creation timestamp', auto_now_add=True)


class Complaint(Model):
    user = ForeignKey(User, on_delete=CASCADE)
    comment = ForeignKey(Comment, on_delete=CASCADE)
    created = DateTimeField(auto_now_add=True)


class View(Model):
    viewer = ForeignKey(User, on_delete=CASCADE)
    blog = ForeignKey(Blog, on_delete=CASCADE)
    created_at = DateTimeField('creation timestamp', auto_now_add=True)

blogger/forms.py
from django import forms
from .models import Post, Blog


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=32)
    password = forms.CharField(label='Password', max_length=128, widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    blog_title = forms.CharField(label='Blog Title', max_length=50)
    avatar = forms.ImageField(label='Avatar', required=False)
    username = forms.CharField(label='Username', max_length=32)
    bio = forms.CharField(label='BIO', max_length=300, required=False, widget=forms.Textarea)
    email = forms.EmailField(label='E-Mail', max_length=128)
    permission = forms.BooleanField(label='Permission', required=False)
    password = forms.CharField(label='Password', min_length=8, max_length=128, widget=forms.PasswordInput)
    password_again = forms.CharField(label='Password, again', min_length=8, max_length=128, widget=forms.PasswordInput)


class PostForm(forms.ModelForm):
    subject = forms.CharField(max_length=50)
    text = forms.CharField(max_length=1000, widget=forms.Textarea)
    address = forms.CharField(max_length=80)

    # def __init__(self, *args, **kwargs):
    #     blog_id = kwargs.pop('blog_id', '')
    #     super(PostForm, self).__init__(*args, **kwargs)   #what is this shit
    #     if blog_id:
    #         self.fields['blog'].initial = blog_id

    class Meta:
        model = Post
        fields = ['subject', 'text', 'address', 'photo']
        # widgets = {'blog': forms.HiddenInput()}

    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #     self.fields['text'].widget.attrs.update({'class': 'postTextField'})


# class CommentForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = ['comment_post']

class BlogEditForm(forms.ModelForm):
    title = forms.CharField(max_length=50)
    bio = forms.CharField(max_length=300, widget=forms.Textarea)

    class Meta:
        model = Blog
        fields = ['title', 'avatar', 'bio', 'permission']

blogger/views.py
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages

from .models import Blog, Post, Comment, Like, View, Follow, Complaint
from .forms import LoginForm, RegistrationForm, PostForm, BlogEditForm


def log_out(request):
    logout(request)
    redirect_url = request.GET.get('next') or reverse('index')
    return redirect(redirect_url)


def log_in(request):
    if request.method == 'POST':
        logout(request)
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(request.GET['next'])
            else:
                messages.error(request, 'username or password not correct')
                return redirect('login')
                # form.add_error('Invalid credentials!')
    else: # GET
        form = LoginForm()
    return render(request, 'blogger/login.html', {'form': form})


def sign_up(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST,  request.FILES)
        if form.is_valid():
            logout(request)
            blog_title = form.cleaned_data['blog_title']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            avatar = form.cleaned_data['avatar']
            permission = form.cleaned_data['permission']
            bio = form.cleaned_data['bio']
            password = form.cleaned_data['password']
            password_again = form.cleaned_data['password_again']
            if User.objects.filter(username=username).exists():
                form.add_error('username', 'User already exists!')
            elif password != password_again:
                form.add_error('password_again', 'Passwords mismatch!')
            else:
                user = User.objects.create_user(username, email, password)
                if avatar: #and bio:
                    blog = Blog.objects.create(author=user, title=blog_title, avatar=avatar, permission=permission, bio=bio)
                elif bio:
                    blog = Blog.objects.create(author=user, title=blog_title, permission=permission, bio=bio)
                elif avatar:
                    blog = Blog.objects.create(author=user, title=blog_title, permission=permission, avatar=avatar)
                else:
                     blog = Blog.objects.create(author=user, permission=permission, title=blog_title)
                login(request, user)
                context = {'blog': blog, 'posts': []}
                return render(request, 'blogger/blog.html', context)
    else: # GET
        form = RegistrationForm()
    return render(request, 'blogger/signup.html', {'form': form})


def get_blog_list(request):
    search_query = request.GET.get('search', '')
    if search_query:
        blogs = Blog.objects.filter(title__icontains=search_query).order_by('-created_at')
    else:
        blogs = Blog.objects.order_by('-created_at')
    context = {'blogs': blogs}
    return render(request, 'blogger/index.html', context)


@login_required(login_url='/blogger/login')
def blog(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    if request.method == 'POST':
        return follow(request, blog_id)
    if blog.author_id != request.user.id:
        new_view, created = View.objects.get_or_create(viewer=request.user, blog_id=blog_id)
        if created:
            blog.views = blog.views + 1
            blog.save()

    return render_blog(request, blog_id)


def render_blog(request, blog_id, additional_context={}):
    blog = get_object_or_404(Blog, id=blog_id)
    comments=[]
    for post in blog.post_set.order_by('-created_at'):
        for comment in post.comment_set.order_by('-created_at'):
            comments.append(comment)
    if blog.author_id != request.user.id:
        if Follow.objects.filter(following=blog.author, follower=request.user).exists():
            context = {
                'blog': blog,
                'posts': blog.post_set.order_by('-created_at'),
                'comments': comments,
                'is_followed':True,
                **additional_context
            }
            return render(request, 'blogger/blog.html', context)
        else:
            context = {
                'blog': blog,
                'posts': blog.post_set.order_by('-created_at'),
                'comments': comments,
                'is_followed': False,
                **additional_context
            }
            return render(request, 'blogger/blog.html', context)
    else:
        context = {
            'blog': blog,
            'posts': blog.post_set.order_by('-created_at'),
            'comments': comments,
            **additional_context
        }
    return render(request, 'blogger/blog.html', context)


def create_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    comment_post = request.POST['comment_post']
    comment_post_error = None
    if not comment_post or comment_post.isspace():
        comment_post_error = 'Please provide non-empty comment!'

    if len(comment_post) > 300:
        comment_post_error='Please make comment shorter!'

    if comment_post_error:
        error_context = {
            'comment_post_error': comment_post_error,
            'comment_post': comment_post
        }
        return render_blog(request, post.blog.id, error_context)
    else:
        Comment(comment_post=comment_post, author=request.user, commented_image=post).save()
        return HttpResponseRedirect(reverse('blog_by_id', kwargs={'blog_id': post.blog.id}))
        #return render(request, 'blogger/blog.html', {'blog': blog})


def create_post_(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    if request.method == 'POST':
        if blog.author_id != request.user.id:
            return HttpResponseForbidden('You are not allowed to post in this blog!')
        form = PostForm(request.POST, request.FILES) #, blog_id=blog.id)
        #form = PostForm(request.POST, request.FILES, blog_id=blog.id)
        if form.is_valid():
            # form.blog = blog
            post = form.save(commit=False)
            post.blog = blog
            post.save()
            # Get the current instance object to display in the template
            img_obj = form.instance
            # return render(request, 'blogger/create_post_.html', {'form': form, 'img_obj': img_obj})
            return HttpResponseRedirect(reverse('blog_by_id', kwargs={'blog_id': blog_id}))
    else:
        form = PostForm()#(blog_id=blog.id)
    return render(request, 'blogger/create_post_.html', {'blog_id':blog_id ,'form': form})


def edit_blog(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    # if request.method == 'POST':
    if blog.author_id != request.user.id:
        return HttpResponseForbidden('You are not allowed to post in this blog!')
    if 'Delete_blog' == request.GET.get('name'):
        return delete_user(request)
    else:
        form = BlogEditForm(request.POST or None, request.FILES or None, instance=blog)  # , blog_id=blog.id)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.save()
            return HttpResponseRedirect(reverse('blog_by_id', kwargs={'blog_id': blog_id}))

                # return delete_user(request)
        else:
            form = BlogEditForm(instance=blog)  # (blog_id=blog.id)

    return render(request, 'blogger/edit_blog.html', {'blog_id': blog_id, 'form': form})


def delete_user(request):
    user = get_object_or_404(User, id=request.user.id)
    logout(request)
    user.delete()   # or save edits
    # return get_blog_list(request)
    return HttpResponseRedirect(reverse('index'))


def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        # if 'Like' in request.POST:
        if 'Like' == request.GET.get('name'):
            new_like, created = Like.objects.get_or_create(user=request.user, post_id=post_id)
            if not created:
                post.likes = post.likes - 1
                post.save()
                Like.objects.get(user=request.user, post_id=post_id).delete()
                return HttpResponseRedirect(reverse('blog_by_id', kwargs={'blog_id': post.blog.id}))
                # the user already liked this picture before
            else:
                post.likes = post.likes + 1
                post.save()
                return HttpResponseRedirect(reverse('blog_by_id', kwargs={'blog_id': post.blog.id}))
            # oll korrekt
        elif 'Edit_post' == request.GET.get('name'):
            return edit_post(request, post_id)
        elif 'Delete_post' == request.GET.get('name'):
            return delete_post(request, post_id)
        else:
            return create_comment(request, post_id)
    else:
        return render_blog(request, post.blog.id)


def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
     # , blog_id=blog.id)
    if post.blog.author_id != request.user.id:
        return HttpResponseForbidden('You are not allowed to post in this blog!')
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    # form = PostForm(request.POST, request.FILES, blog_id=blog.id)
    if form.is_valid():
        # form.blog = blog
        post = form.save(commit=False)
        post.save()
        return HttpResponseRedirect(reverse('blog_by_id', kwargs={'blog_id': post.blog.id}))
    else:

blogger/templates/blogger/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Blogger{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/welcome.css' %}">
</head>
<body>
<div>
<!--    <form action="{% url 'logout' %}?next={{ request.path }}"  method="POST" style="display:inline; padding:10px;">-->
<!--            {% csrf_token %}-->
<!--            <input type="image" value="LogOut" class="buttonLike" src="/static/css/img/exit.png" height="40px"/>-->
<!--            </form>-->
</div>
<div class="mainTop">
      {% if request.user.is_authenticated %}
    <div class="logout" style="float:right;"><form action="{% url 'logout' %}?next={{ request.path }}"  method="POST" style="display:inline; padding:10px;">
            {% csrf_token %}
            <input type="image" value="LogOut" class="buttonLike" src="/static/css/img/exit.png" height="40px"/>
            </form>
    </div>
      <a href="{% url 'index' %}">  <img src="/static/css/img/house8.png" alt="house_welcome"></a>

    {% with user.blog_set.all|first as blog %}
        <a href="{% url 'blog_by_id' blog.id %}">
            <img src="{{blog.avatar.url}}" alt="My blog" style="height: 90px;
                            width: 90px;
                            margin: 8px 0px 0px 60px;
                            padding: 0;
                            border-radius: 50%;"/> <div class="base" style="margin-right: 900px;"> Welcome, {{ request.user.username }}!</div></a>
    <div class="create"><button class="button"><a href="{% url 'create_post_' blog.id %}">Create Post</a></button></div>


    {% endwith %}

      {% else %}
      <a href="{% url 'index' %}">  <img src="/static/css/img/house8.png" alt="house_welcome"></a>
      <p class="base">Welcome, stranger! Please
          <button class="button"><a href="{% url 'login' %}?next={{ request.path }}">Log in</a></button>
          or
          <span class="base"><button class="button"><a href="{% url 'signup' %}">Sign up</a></button></span>
      </p>
      {% endif %}
  </div>
    <div class="search-v">
    <form  action="{% url 'index' %}" style="float: right; margin-right: 50px;">
        <input  type="search" placeholder="Search" aria-label="Search" name="search" size="110" style="font-size:20px; height:45px; border-radius: 1em; padding-left:15px;
                                                                                                       border: 2px solid #604020; margin-right:20px;">
        <button type="submit" class="button" style="border: 3px solid #604020;
                                                    color: #604020;"> Search </button>
        </form>
    </div>
{% if not request.user.is_authenticated %}
<div class="mainNotTop">

        <p class="site-info">Here you can read everything about old houses - about their history, architecture, owners and much more! </p>
            <p class="site-info">You can also create your own posts if you have something to share. </p>
            <img src="/static/css/img/house.png" alt="house_welcome">

</div>
{% endif %}
{% block content %}{% endblock %}
</body>
</html>

blogger/templates/blogger/blog.html
{% extends 'blogger/base.html' %}
{% block title %}{{ blog.title }}{% endblock %}
{% block content %}
{% load static %}
<!--{% if blog.author_id == request.user.id %}-->

<!--<button class="button"><a href="{% url 'create_post_' blog.id %}">Create Post</a></button><br><br><br>-->
<!--{% endif %}-->

<!--<span class="mainBlogInfo" style="font-size: 30px; padding: 10px; margin-left: 80px; margin-right: 10px;">{{ blog.views}}</span>-->
<!--<img src="/static/css/img/search.png" width="30px">-->
<!--<span style="font-size: 30px; padding: 20px;">{{ blog.post_set.count }}</span>-->
<!--<img src="/static/css/img/mailbox.png" width="30px">-->
<div class="mainPost row" style="width: 92%;">
    <div class="columnPhoto"
         style="float: left;
               width: 13%;
               ">
    <img src="{{blog.avatar.url}}" alt="" width="250" height="250" class="photo"
                    style="height: 150px;
                            width: 150px;
                            margin: 30px 0px 30px 30px;
                            padding: 0px 0px 0px 0px;
                            border-radius: 10%;
                            "/>
        </div>
    <div class="column" style="float: right;
                                width: 25%;
                                padding-top: 150px;
                                margin-right: -150px;
                                padding-bottom: 10px;">

        <span class="mainBlogInfo" style="font-size: 30px; padding: 10px; margin-left: 80px; margin-right: 10px;">{{ blog.views}}</span>
    <img src="/static/css/img/search.png" width="30px">
<span style="font-size: 30px; padding: 20px;">{{ blog.post_set.count }}</span><img src="/static/css/img/mailbox.png" width="30px">
    </div>
    {% if blog.author_id == request.user.id %}
    <div class="edit" style="margin-right:-250px;"><form action="{% url 'edit_blog' blog.id %}?name=Edit_blog"  method="POST" style="display:inline; padding:10px;">
            {% csrf_token %}
            <input type="image" value="Edit" class="buttonLike" src="/static/css/img/edit.png" height="20px"/>
            </form>
            </div>
    {% endif %}

    <div class="columnMainInfo" style="float: left;
                                        width: 15%;
                                        padding-top: 70px; font-size: 20px;">
        <span><b>Title:</b> {{blog.title}}</span> <br>
        <span><b>Bio:</b> {{blog.bio}}</span>
    {% if blog.permission %}
        <br><span> <b>Email:</b> {{blog.author.email}} </span>
    {% endif %}
    </div>
    <div style="float: left; width: 15%; padding-left:20px; padding-top: 70px; font-size: 20px;
                                padding-bottom: 10px;">
        <span><b>Followers:</b>  <a href="{% url 'list' blog.id %}?name=Followers">  {{ blog.author.following.count }} </a> </span>
    <br>
        <span><b>Following:</b>  <a href="{% url 'list' blog.id %}?name=Following"> {{ blog.author.follower.count }}  </a> </span>
    </div>


<!--    <div style="float: left; width: 25%; padding-top: 20px; font-size: 20px;-->
<!--                                padding-bottom: 10px;">-->
            {% if blog.author.id != request.user.id %}
        <div style="float:right; margin-right:-220px;">
        {% if is_followed %}
        <form action="{% url 'blog_by_id' blog.id %}"  method="POST" style="display: inline;">
                     {% csrf_token %}
                    <input type="submit" class="follow" align="center" value="Unfollow" style="color: #60401f;
                                                                                               border: 3px solid #60401f;
                                                                                      cursor: pointer;
                                                                                    background: linear-gradient(to right, #cd9965, #e0bf9f);
                                                                                    font-family: 'Ubuntu', sans-serif;
                                                                                    font-size: 20px;"/>
                </form>
            {% else %}
        <form action="{% url 'blog_by_id' blog.id %}"  method="POST" style="display: inline;">
            {% csrf_token %}
            <input type="submit" class="follow" align="center" value="Follow" style="color: #60401f;
                                                                                      border: 3px solid #60401f;
                                                                                      "/>
        </form>
        {% endif %}
            </div>
    {% endif %}



<br/> <br/>

</div>

<ul>
    {% for post in posts %}
    <li class="hide">
        {% if blog.author_id == request.user.id %}
            <div class="edit" style="margin-right:60px; margin-top:20px;">
            <form action="{% url 'post_by_id' post.id %}?name=Edit_post"  method="POST" style="display: inline; padding:10px;">
            {% csrf_token %}
            <input type="image" value="Edit" class="buttonLike" src="/static/css/img/edit.png" height="20px"/>
            </form>

            <form action="{% url 'post_by_id' post.id %}?name=Delete_post"  method="POST" style="display: inline; padding:10px;">
            {% csrf_token %}
            <input type="image" value="Delete" class="buttonLike" src="/static/css/img/delete.png" height="20px"/>
            </form>
            </div>
            {% endif %}
        <div class="mainPost" style="width: 94%; margin-left: 50px;">
        <p><img src="{{post.photo.url}}" alt="" width="300" height="300" class="imgPost"/></p>
            <div class="postInfo">
                    <img src="/static/css/img/calendar.png" width="40px">
                    <span class="postT">Created at:</span> <i>{{ post.created_at }}</i>
                <br><br>

                <img src="/static/css/img/business-and-finance.png" width="40px">
                <span class="postT">Post subject:</span> {{ post.subject }}<br><br>
                <img src="/static/css/img/branding.png" width="40px">
                <span>
                    <span class="postT">Story:</span>
                    <span id="postTextField">{{ post.text }}</span>
                </span><br><br>
                <img src="/static/css/img/home-address.png" width="40px">
                <span class="postT">Address of building:</span> {{ post.address }}
                </div>

                 <span style="float:right; margin-right:30px; font-weight: 600; font-size: 20px;">
            <form action="{% url 'post_by_id' post.id %}?name=Like"  method="POST" style="display: inline; padding:10px;">
            {% csrf_token %}
            <input type="image" value="Like" class="buttonLike" src="/static/css/img/like.png" height="20px"/>
            </form>
                    {{post.likes}}
                </span>
                <br><br>
        </div>
    </li>
    <div>
    {% for comment in comments %}
            {%if comment.commented_image.id == post.id %}
            <div class="row comments" style="width: 93%; margin-left: 50px;">
                <div class="columnImg">
                    <img src="/static/css/img/message.png" width="40px">
                </div>
              <div class="columnAuth">
                  {{ comment.author }}<br>
                  At: {{ comment.created_at }}
              </div>
              <div class="column">
                  {{ comment.comment_post }}
              </div>
        <div style="float:right; padding-right:15px;">

            {%if comment.author.id != request.user.id %}
        <form action="{% url 'complaint' comment.id %}"  method="POST" style="display: inline; padding:10px;">
        {% csrf_token %}
        <input type="image" value="complaint" class="buttonLike" src="/static/css/img/compl.png" height="20px"/>
        </form>
            {%else%}
            <img class="buttonLike" src="/static/css/img/compl.png" height="20px" style="padding:0px 10px;">
            {% endif %}
            {{comment.complaints}}
         </div>
        </div>
            </div>
        {%endif%}

        {% endfor %}
    </div>

    <div class="row postComment" style="width: 93%; margin-left: 50px;">
        <div class="columnImg">
            <img src="/static/css/img/message.png" width="40px">
        </div>
        <form action="{% url 'post_by_id' post.id %}" method="POST" >
            <div class="columnInput">
            {% csrf_token %}
            <textarea name="comment_post" maxlength="4096" rows="10" cols="80" placeholder="Post comment">{{ comment_post }}</textarea>
            {% if text_error %}
            <p style="color:red;">{{ text_error }}</p>
            {% endif %}
            </div>
            <div class="columnButton">
            <input type="image" value="Create comment" class="buttonComment" src="/static/css/img/send.png"/>
            </div>
        </form>
    </div>
    {% endfor %}
</ul>

{% endblock %}

blogger/templates/blogger/create_post_.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Create post</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/welcome.css' %}">
</head>
<body>
    <div class="mainC">
        <a href="{% url 'blog_by_id' blog_id %}"><img class="back" src="/static/css/img/sign.png" alt="back"></a>
        <p class="sign">Create post</p>
    <form class="form1" method="POST" enctype="multipart/form-data" style="margin-right: 300px;">
      {% csrf_token %}
       <table type="text" align="center" class="un create">{{ form }}</table>
      <input type="submit" class="submit" align="center" value="Upload">
    </form>

{% if img_obj %}
  <p class="ask">Succesfully uploaded</p>
{% endif %}
    </div>>
</body>
</html>

blogger/templates/blogger/edit_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Create post</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/welcome.css' %}">
</head>
<body>
    <div class="mainC">
        <a href="{% url 'blog_by_id' blog_id %}"><img class="back" src="/static/css/img/sign.png" alt="back"></a>
        <p class="sign">Edit blog</p>
    <form class="form1" method="POST" enctype="multipart/form-data" style="margin-right: 300px;">
      {% csrf_token %}
       <table type="text" align="center" class="un create">{{ form }}</table>
      <input type="submit" class="submit" align="center" value="Upload">
    </form>
        <br/>


        <div style="margin-top: 350px;"><a href="{% url 'edit_blog' blog_id %}?name=Delete_blog" onclick="return confirm('Are you sure you want to delete this?')">Delete account?</a></div>


    </div>
</body>
</html>

blogger/templates/blogger/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Create post</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/welcome.css' %}">
</head>
<body>
    <div class="mainC">
        <a href="{% url 'blog_by_id' blog_id %}"><img class="back" src="/static/css/img/sign.png" alt="back"></a>
        <p class="sign">Edit post</p>
    <form class="form1" method="POST" enctype="multipart/form-data" style="margin-right: 300px;">
      {% csrf_token %}
       <table type="text" align="center" class="un create" >{{ form }}</table>
      <input type="submit" class="submit" align="center" value="Upload" style="margin-top:100px;">
    </form>

    </div>>
</body>
</html>

blogger/templates/blogger/list.html
{% extends 'blogger/base.html' %}
{% block content %}
<h2 >
    <div style="background-color: #be9063; width: 90%; border-radius: 1.5em; margin-left:5%; padding: 0px 20px 10px 20px;
        box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);">
        <a href="{% url 'blog_by_id' blog.id %}"><img class="back" src="/static/css/img/sign.png" alt="back"
                    style="margin:330px 60px;"></a>
        <br><br>
        <ul class="av">
    {% if user_follow %}
        {% for follow_user in user_follow %}
            {% with follow_user.blog_set.all|first as follow_blog %}
        <li class="hide mainAvatar">
    <table style="margin-left: 1%; border-radius: 20px; background-color: #f2e6d9; margin-bottom:20px; padding-left:10px;">
    <td><img src="{{follow_blog.avatar.url}}" alt="" class="photo"
                style="height: 50px;
                            width: 50px;
                            margin:0;
                            padding: 0;
                            border-radius: 50%;
                            "/></td>
            <td style="width: 600px;"><a href="{% url 'blog_by_id' follow_blog.id %}" class="blogName">{{ follow_blog.title }}</a></td>
            <td style="width: 300px"> Posts: {{follow_blog.post_set.count}} </td>
                <td style="width: 300px"> Views: {{follow_blog.views}} </td>
                <td style="width: 300px"> Followers: {{follow_blog.author.following.count}} </td>
                <td style="width: 300px"> Following: {{follow_blog.author.follower.count}} </td>
            {%endwith%}
    </table>
            </li>
        {% endfor %}
            {%else%}
            <img src="/static/css/img/cat.png" alt="empty" width="500px" style="margin-left: 35%;">
            {%endif%}
        </ul>

    </div>
</h2>
{% endblock %}